# Generated by Django 4.2.1 on 2023-05-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='Id',
            new_name='id',
        ),
    ]
