# Generated by Django 4.2.1 on 2023-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_rename_id_ads_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
