# Generated by Django 4.2.1 on 2023-05-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_ads_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
    ]
