# Generated by Django 4.2.1 on 2023-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_user_age_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
