# Generated by Django 4.2.1 on 2023-05-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_user_location_user_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='locations',
            new_name='location',
        ),
    ]
